### ISSUE TITLE
Ability to select the live session or installer (ideally in a way that is accessible and possible using Bluetooth input devices)

### ISSUE THREAD

**Issue by M4rtinK** [rhinstaller/anaconda-webui#3]
Workstation tracker issue: https://pagure.io/fedora-workstation/issue/370

**Comment by M4rtinK** [comment]
Looks like these could be about the current splash screen that gives the user the option to install or use the live environment ?

**Comment by jkonecny12** [comment]
I think the current splash screen is exactly that. Ask SIG if we are able to close this.

**Comment by jkonecny12** [comment]
Closed by Workstation SIG - not related to the Web UI proposal.
